
CC = gcc
OBJS = processM.c
COMPILER_FLAGS = -Wall

OBJ_NAME = processM

#This is the target that compiles our executable
all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) -o $(OBJ_NAME) 
    # ./$(OBJ_NAME) 
