
CC = gcc
OBJS = myFind.c
COMPILER_FLAGS = -Wall

OBJ_NAME = myFind

#This is the target that compiles our executable
all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) -o $(OBJ_NAME) 
    # ./$(OBJ_NAME) 
