
CC = gcc
OBJS = program.c
COMPILER_FLAGS = -Wall -pthread -lrt 

OBJ_NAME = program

#This is the target that compiles our executable
all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) -o $(OBJ_NAME) 
    # ./$(OBJ_NAME) 
